# Generated by Django 2.2.12 on 2021-09-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_courses_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='photo',
            field=models.ImageField(null='true', upload_to='pics'),
            preserve_default='true',
        ),
    ]
