# Generated by Django 2.2.12 on 2021-09-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_teachers_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='Image1',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Image2',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Image3',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='photo',
            field=models.ImageField(null='true', upload_to='media'),
        ),
    ]
